import { expect, test } from '@playwright/test';

test('local branding, photo, paused menu, cash movements, receipts and backup without external services', async ({ browser }) => {
  const context = await browser.newContext();
  const external: string[] = [];
  await context.route('**/*', route => {
    const url = new URL(route.request().url());
    if (url.hostname !== '127.0.0.1') { external.push(url.href); return route.abort(); }
    return route.continue();
  });
  const page = await context.newPage();
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/#/staff');
  await page.getByLabel('Usuario', { exact: true }).fill('admin');
  await page.getByLabel('Contraseña', { exact: true }).fill('Solo-Pruebas-2026!');
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click();
  await page.getByRole('button', { name: 'Mi negocio', exact: true }).click();
  await page.getByLabel('Nombre del local').fill('Café Local');
  const photo = await page.screenshot();
  await page.getByLabel('Logo del negocio', { exact: true }).setInputFiles({ name: 'logo.png', mimeType: 'image/png', buffer: photo });
  await expect(page.getByAltText('Vista previa: Logo del negocio')).toBeVisible();
  await page.getByLabel('Color principal HEX', { exact: true }).fill('#803399');
  await page.getByLabel('Color de acento HEX', { exact: true }).fill('#ffaa22');
  await page.getByLabel('Horario de atención').fill('Lunes a sábado, 8 a 6');
  await page.getByRole('button', { name: 'Guardar cambios', exact: true }).click();
  await expect(page.getByText('Configuración guardada.')).toBeVisible();
  await expect(page.locator('.sidebar .brand strong')).toHaveText('Café Local');
  await page.reload();
  await expect(page.locator('.sidebar .brand-logo')).toBeVisible();
  await expect(page.locator('.themed-app')).toHaveCSS('--green', '#803399');
  await page.getByRole('button', { name: 'Productos', exact: true }).click();
  await page.getByRole('button', { name: 'Nuevo producto', exact: true }).click();
  await page.getByLabel('Nombre', { exact: true }).fill('Producto con foto');
  await page.getByLabel('Precio final (₡)').fill('1500');
  await page.getByLabel('Foto del producto', { exact: true }).setInputFiles({ name: 'producto.png', mimeType: 'image/png', buffer: photo });
  await expect(page.getByAltText('Vista previa: Foto del producto')).toBeVisible();
  await page.getByLabel('Destacar en el menú').check();
  await page.getByLabel('Alérgenos e información alimentaria').fill('Contiene leche');
  await page.getByRole('button', { name: 'Guardar producto', exact: true }).click();
  await expect(page.getByText('★ Producto con foto', { exact: true })).toBeVisible();
  const menu = await context.newPage();
  await menu.goto('/');
  await expect(menu.locator('.brand-logo')).toBeVisible();
  await expect(menu.getByText('Lunes a sábado, 8 a 6')).toBeVisible();
  const product = menu.locator('.product-card').filter({ hasText: 'Producto con foto' });
  await expect(product.getByRole('img', { name: 'Producto con foto', exact: true })).toBeVisible();
  await product.getByText('Información alimentaria').click();
  await expect(product.getByText('Contiene leche')).toBeVisible();
  await menu.screenshot({ path: 'test-results/local-menu.png', fullPage: true });
  await page.getByRole('button', { name: 'Mi negocio', exact: true }).click();
  await page.getByLabel('Recibir nuevos pedidos').uncheck();
  await page.getByLabel('Mensaje al pausar pedidos').fill('Volvemos pronto');
  await page.getByRole('button', { name: 'Guardar cambios', exact: true }).click();
  await expect(page.getByText('Configuración guardada.')).toBeVisible();
  await menu.reload();
  await expect(menu.getByText('Volvemos pronto')).toBeVisible();
  await menu.getByRole('button', { name: 'Agregar Producto con foto', exact: true }).click();
  await expect(menu.getByRole('button', { name: 'Confirmar pedido', exact: true })).toBeDisabled();
  await page.getByLabel('Recibir nuevos pedidos').check();
  await page.getByRole('button', { name: 'Guardar cambios', exact: true }).click();
  await expect(page.getByText('Configuración guardada.')).toBeVisible();
  await page.getByRole('button', { name: 'Crear respaldo ahora', exact: true }).click();
  await expect(page.getByText('Respaldo completo creado. Ya podés descargarlo.')).toBeVisible();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: /^Descargar soda-/ }).first().click();
  expect((await download).suggestedFilename()).toMatch(/\.zip$/);
  await page.getByRole('button', { name: 'Noche', exact: true }).click();
  await page.screenshot({ path: 'test-results/local-settings.png', fullPage: true });
  await page.getByRole('button', { name: 'Turno de caja', exact: true }).click();
  await page.getByLabel('Fondo inicial en efectivo (₡)').fill('1000');
  await page.getByRole('button', { name: 'Abrir caja', exact: true }).click();
  await page.getByLabel('Monto del movimiento (₡)').fill('100');
  await page.getByLabel('Motivo del movimiento').fill('Compra de hielo');
  await page.getByRole('button', { name: 'Registrar movimiento', exact: true }).click();
  await expect(page.getByText('Movimiento registrado.')).toBeVisible();
  await expect(page.locator('.totals')).toContainText('900');
  await page.getByLabel('Efectivo contado al cierre (₡)').fill('900');
  await page.getByRole('button', { name: 'Confirmar cierre de caja', exact: true }).click();
  await expect(page.getByText('Cuadra', { exact: true }).first()).toBeVisible();
  await menu.reload();
  await menu.getByRole('button', { name: 'Agregar Producto con foto', exact: true }).click();
  await menu.getByRole('button', { name: 'Confirmar pedido', exact: true }).click();
  await expect(menu.getByRole('heading', { name: 'Pasá a caja a pagar.' })).toBeVisible();
  await menu.evaluate(() => {
    window.print = () => { document.body.dataset.printed = document.querySelector('.print-receipt')?.textContent || ''; };
  });
  await menu.getByRole('button', { name: 'Imprimir recibo' }).click();
  await expect(menu.locator('body')).toHaveAttribute('data-printed', /No es un comprobante electrónico tributario/);
  await menu.getByRole('button', { name: 'Hacer otro pedido' }).click();
  await menu.setViewportSize({ width: 390, height: 844 });
  await menu.screenshot({ path: 'test-results/local-mobile.png', fullPage: true });
  expect(await menu.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(external).toEqual([]);
  expect(errors).toEqual([]);
  await context.close();
});
